name: 'Environment Variables'

on:
    workflow_dispatch: 

env:
    DAY_OF_WEEK: Funday
    testvar: value-1

jobs:
    mainjob:
        name: 'Print'
        runs-on: ubuntu-latest

        env:
            Greeting: Dear
            testvar: value-2

        steps:
            - name: print-values-of-variables
              run: |
                echo "Greeting $First_Name. Today is $DAY_OF_WEEK!"
                echo "testvar $testvar"
                echo "testvar ${{ env.testvar }}"
              env:
                First_Name: Student
                testvar: value-3